sudo: false

language: node_js

node_js:
  - 0.10
  - 4
  - 5
  - iojs

after_success: npm install coveralls mocha-lcov-reporter && NODE_ENV=test ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha  --report lcovonly -- --recursive -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
